### ISSUE TITLE
npc.invader.battle is missing

### ISSUE THREAD

**Issue by RobDaPraia** [Sriep/screeps#1]
Thanks for the code :)

Seems that the file npc.invader.battle is missing?

Used in policy.defense.js: 

var npcInvaderBattle = require("npc.invader.battle");

**Comment by ChrisTaylorRocks** [comment]
I am having the same issue 'npc.invader.battle' is missing.

**Comment by Sriep** [comment]
Removed reference to npc.invader.battle
